// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const CredentialKeysSchema = z.object({
  id: z.string().uuid(),
  kmsSecretManagerEncryptedDataKey: zodBuffer,
  kmsSecretManagerKeyId: z.string().uuid(),
  userId: z.string().uuid(),
  orgId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TCredentialKeys = z.infer<typeof CredentialKeysSchema>;
export type TCredentialKeysInsert = Omit<z.input<typeof CredentialKeysSchema>, TImmutableDBKeys>;
export type TCredentialKeysUpdate = Partial<Omit<z.input<typeof CredentialKeysSchema>, TImmutableDBKeys>>;
